name: Main

on: 
  workflow_dispatch:
    inputs:
      tileset:
        description: Tile region to generate
        type: choice
        options:
          - asi
          - afr
          - sa
          - na
          - aus_pac
          - eur
          - test  
      zl:
        description: zoom level of the ortho
        type: string
        default: '16'
      relname:
        description: Release Name
        type: string
        default: ''


jobs:
  ziplist:
    runs-on: ubuntu-latest
    outputs:
      chunks: ${{ steps.chunks.outputs.chunks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gen tile sub-lists
        id: chunks
        run: |
          TILENAME=${{ inputs.tileset }} make -f Makefile.tiles ${{ inputs.tileset }}_tile_list_chunks
          CHUNKS=$(ls ${{ inputs.tileset }}_tile_list.* | awk -F '.' '/.+/ { printf "%s\"z_${{ inputs.tileset }}_%s.zip\"", sep, ""$2""; sep=", " }')
          #CHUNKS=$(ls ${{ inputs.tileset }}_tile_list.* | awk -v ORS=',' '{print $1}')
          echo "chunks={\"chunk\":[$CHUNKS]}" >> $GITHUB_OUTPUT


  call-build:
    needs: ziplist

    strategy:
      matrix: ${{ fromJSON(needs.ziplist.outputs.chunks) }}

    uses: ./.github/workflows/build-tiles.yml
    with:
      zip: ${{ matrix.chunk }}
      setname: ${{ inputs.tileset }}
      relname: ${{ inputs.relname }}     


  info:
    #if: startsWith(github.ref, 'refs/tags/')
    needs: call-build

    # environment: release

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.tileset }}_info.json
          tag_name: ${{ inputs.relname }}     

