name: Build one .zip (and upload)

on:
  workflow_dispatch:
    inputs:
      tileset:
        description: Tile region to generate
        type: choice
        options:
          - asi
          - afr
          - sa
          - na
          - aus_pac
          - eur
          - test  
      zl:
        description: Zoom level of the ortho
        type: string
        default: '16'
      relname:
        description: Release Name
        type: string
        default: ''
      zipnum:
        description: Zip iteration number
        type: string
        required: true

jobs:
  call-build:
    uses: ./.github/workflows/build-tiles.yml
    with:
      zip: z_${{ inputs.tileset }}_${{ inputs.zipnum }}.zip
      setname: ${{ inputs.tileset }}
      relname: ${{ inputs.relname }} 
